backend:
  name: github
  repo: sakelog/sake_log
  branch: master
publish_mode: editorial_workflow
media_folder: "img/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {labl: "Update", name: "update", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}