backend:
  name: github
  repo: sakelog/sake_log
  branch: master
publish_mode: editorial_workflow
media_folder: 'content/post/img/upload'
public_folder: '/img/upload'
collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/post'
    create: true
    slug: '{{fields.slug}}'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', dateFormat: 'YYYY-MM-DD', timeFormat: 'HH:mm:ss' }
      - {
          label: 'Update',
          name: 'update',
          default: '',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm:ss',
          required: false,
        }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: 'true' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'page'
    label: 'page'
    folder: 'content/page'
    create: true
    slug: '{{fields.slug}}'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', dateFormat: 'YYYY-MM-DD', timeFormat: 'HH:mm:ss' }
      - {
          label: 'Update',
          name: 'update',
          default: '',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm:ss',
          required: false,
        }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
