backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: 'content/post/img/upload'
public_folder: '/img/upload'
locale: 'ja'
collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/post'
    create: true
    extension: 'md'
    slug: '{{fields.slug}}'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD HH:mm',
        }
      - {
          label: 'Update',
          name: 'update',
          default: '',
          widget: 'datetime',
          format: 'YYYY-MM-DD HH:mm',
          required: false,
        }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - {
          label: 'Category',
          name: 'category',
          widget: 'relation',
          collection: 'categorylist',
          searchFields: '{{name}}',
          valueField: 'name',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          minimize_collapsed: true,
          summary: '{{fields.tag}}',
          field: { label: Tag, name: tag, widget: 'string' },
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'page'
    label: 'Page'
    folder: 'content/page'
    create: true
    extension: 'md'
    slug: '{{fields.slug}}'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD HH:mm',
        }
      - {
          label: 'Update',
          name: 'update',
          default: '',
          widget: 'datetime',
          format: 'YYYY-MM-DD HH:mm',
          required: false,
        }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'categorylist'
    label: 'Category'
    identifier_field: name
    create: true
    extension: 'yml'
    folder: 'content/category'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text', required: false}
